<?php


namespace App\Views;

use App\App;
use Core\View;

class Navigation extends View
{
    public function render($template_path = ROOT . '/app/templates/nav.php')
    {
        return parent::render($template_path); // TODO: Change the autogenerated stub
    }

    public function __construct()
    {
        parent::__construct($this->generate());
    }

    public function generate()
    {
        $nav = ['HOME' => '/index.php'];
        if (App::$session->getUser()) {
            return $nav + [
                    'ADD' => '/admin/add.php',
                    'LIST' => '/admin/list.php',
                    'LOGOUT' => '/logout.php',
                ];
        } else {
            return $nav + [
                    'REGISTER' => '/register.php',
                    'LOGIN' => '/login.php',
                ];
        }

    }

}
