<?php


namespace App\Views;

use App\App;
use Core\View;

class Navigation extends View
{

    public function __construct()
    {
        parent::__construct($this->generate());
    }

    public function generate()
    {
        $nav = ['HOME' => App::$router::getUrl('index')];

        if (App::$session->getUser()) {
            return $nav + [
                    'ADD' => App::$router::getUrl('add'),
                    'LIST' => App::$router::getUrl('list'),
                    'LOGOUT' => App::$router::getUrl('logout'),
                ];
        } else {
            return $nav + [
                    'REGISTER' => App::$router::getUrl('register'),
                    'LOGIN' => App::$router::getUrl('login'),
                ];
        }
    }

    public function render($template_path = ROOT . '/app/templates/nav.php')
    {
        return parent::render($template_path); // TODO: Change the autogenerated stub
    }

}
